### ISSUE TITLE
Stuck while flashing "Switching to flash mode"

### ISSUE THREAD

**Issue by Sisu88** [OpenAcousticDevices/AudioMoth-Flash-App#3]
I executed the Audiomoth Flash App 1.0.0 (windows 10) and I wanted to install the new firmware 1.6.0
The flashing has been stuck for more than 30 minutes.
![Audiomoth_Flash_App_error](https://user-images.githubusercontent.com/87916019/126881984-f8a026bc-c6df-481f-b9ff-ded99cd7100c.JPG)

**Comment by Sisu88** [comment]
I killed the AudioMoth Flash App. I think I choosed the false mode. Is that the right current instruction for the AudioMoth 1.2.0? https://docs.wixstatic.com/ugd/d97703_9ac305905bdd4cdfab6aee99767a56e6.pdf

**Comment by pcprince** [comment]
For all versions of Audiomoth, use the latest version of the Flash App. It can be downloaded [here](https://github.com/OpenAcousticDevices/AudioMoth-Flash-App/releases/latest).
